---

# VPC
- name: Gather facts about list of VPC
  ec2_vpc_net_facts:
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
  register: vpc_facts

- name: Print VPC info
  debug:
    var: vpc_facts

- name: Set VPC in variable
  set_fact:
    my_vpc: "{{ item.id }}"
  with_items:
    - "{{ vpc_facts.vpcs }}"
  when:
    - item.is_default != true and item.tags.Generated == "Helmetico"


# SUBNET
- name: Gather facts about list of Subnets filtered by VPC
  ec2_vpc_subnet_facts:
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
      vpc-id: "{{ my_vpc }}"
  register: subnet_facts

- name: Print Subnet info
  debug:
    var: subnet_facts


# ROUTE TABLES
- name: Gather facts about list of Route Tables filtered by VPC and Tag
  ec2_vpc_route_table_facts:
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
      vpc-id: "{{ my_vpc }}"
      "tag:Generated": Helmetico
  register: route_table_facts

- name: Print ROUTE TABLES info
  debug:
    var: route_table_facts


# IGW
- name: Gather facts about a filtered list of Internet Gateways
  ec2_vpc_igw_facts:
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
        "tag:Generated": Helmetico
  register: igw_facts

- name: Print IGW info
  debug:
    var: igw_facts


# NAT
- name: Gather facts about list of NATs filtered by State
  ec2_vpc_nat_gateway_facts:
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
      state: ['available']
  register: nat_facts

- name: Print NAT info
  debug:
    var: nat_facts


# INSTANCES
- name: Gather facts about list of instances filtered by Tag
  ec2_remote_facts:
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
      "tag:Generated": Helmetico
  register: ec2_facts

- name: Print EC2 info
  debug:
    var: ec2_facts

# SECURITY GROUPS
- name: Gather facts about list of Security Groups filtered by VPC
  ec2_group_facts:
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
      vpc-id: "{{ my_vpc }}"
  register: sg_facts

- name: Print SECURITY GROUPS info
  debug:
    var: sg_facts
